# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
# name = "Working Papers"
# url = "#projects"
# weight = 20
  
 [[main]]
 name = "Working Papers"
 url = "#working_paper"
 weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

 #[[main]]
 # name = "(PhD) Notes"
 # url = "PhDNotes/"
 # weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv_AV.pdf"
    weight = 50

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LDL7C4NWBT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-LDL7C4NWBT');
</script>
